version: 0.2

run-as: root

phases:
 install:
    on-failure: ABORT
    runtime-versions:
       python: 3.9
    commands:
      - echo Starting install phase to run the build
      - cd ./ec2manager-lambda-function
      - chmod +x build-ec2manager.sh && ./build-ec2manager.sh
      - cd .. && ls -la